version: "3.9"

services:

  libjaypea:
    depends_on:
      - libjaypea-compile
    container_name: libjaypea
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - ./:/opt/libjaypea
    image: libjaypea:latest
    ports:
      - 80:80

  libjaypea-compile:
    container_name: libjaypea-compile
    build:
      context: ./
      dockerfile: ./dockerfile.compile
    volumes:
      - ./:/opt/libjaypea
    image: libjaypea-compile:latest
